name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:      
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install dependencies
        run: npm ci
      
      - name: Build project
        run: npm run buildProd

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:          
          folder: ./build
          branch: gh-pages
          single-commit: true
